config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  #add admin route to credentials file

  get '/about' => 'static_pages#about'

  #for a little added security, i've hidden my admin login page, using this variable set in my credentials.yml.enc file
  scope Rails.application.credentials.dig(:admin_url) do 
    namespace :admin do
      resources :posts
      resources :downloads
    end
  end

  resources :posts, only: [:index, :show] do
    resources :downloads, only: [:index, :show]
  end
  resources :downloads, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/download.rb
class Download < ApplicationRecord
  has_many :download_posts
  has_many :posts, through: :download_posts
end

app/models/download_post.rb
class DownloadPost < ApplicationRecord
  belongs_to :download
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :download_posts
  has_many :downloads, through: :download_posts
  has_rich_text :body

  scope :published, lambda { where(:published => true) }

  before_validation :sanitize, :slugify

  def slugify
    self.slug = self.title.downcase.gsub(" ", "-").gsub('.', '-')
  end

  def sanitize
    self.title = self.title.strip
  end

  def publishedTime
    self.created_at.to_time.strftime('Published: %B %e,&nbsp; %Y').html_safe
  end

  def truncatePost
    if body
      self.body.to_s.truncate(350, omission: '... (click for more)').html_safe
    end
  end

  def to_param
    self.slug
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  ADMIN = { Rails.application.credentials.ADMIN_USERNAME => Rails.application.credentials.ADMIN_PASSWORD }
  #ADMIN = { "derek" => "frank" }
  before_action :authenticate
  
  def index
    @posts = Post.all
    #@pagy, @posts = pagy(Post.order(:created_at => :asc))
  end

  def show
    @post = Post.find_by(slug: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "Post created"
    else
      render action: "new"
    end
  end

  def edit
    @post = Post.find_by(slug: params[:id])
  end

  def update
    @post = Post.find_by(slug: params[:id])
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post = Post.find_by(slug: params[:id])
    @post.destroy
    flash[:notice] = "Post deleted"
  end

  private
  def authenticate
    authenticate_or_request_with_http_digest do |username|
      ADMIN[username]
    end
  end

  def post_params
    params.require(:post).permit(:title, :body, :thumbnail, :tags, :category, :published, :slug, download_ids:[])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController

  def index
    @downloads = Download.all
  end

  def show
    @download = Download.find(params[:id])
  end

  def new
    @download = Download.new
  end

  def create
    @download = Download.create(download_params)
  end

  def edit
    @download = Download.find(params[:id])
  end

  def update
    @download = Download.find(params[:id])
    @download.update(download_params)
    redirect_to @download
  end

  private
  def download_params
    params.require(:download).permit(:file, :description, post_ids:[])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #include Pagy::Backend

  def index
    #@pagy, @posts = pagy(Post.order(:created_at => :asc))
    #<%== pagy_nav(@pagy) %>, add this to post index page, when pagination becomes necessary
    @posts = Post.published
  end

  def show
    @post = Post.find_by(slug: params[:id])
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    end
  end

  def destroy
    @post = Post.find_by(slug: params[:id])
    @post.destroy
    redirect_to :index
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :thumbnail, :tags, :category, :published, :slug, download_ids:[])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include Pagy::Frontend
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_fit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% end %>
  </figcaption>
</figure>

app/views/admin/posts/_edit_post_form.html.erb
<%= form_for(@post, url: admin_post_path(@post)) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <div style="background:#FFFFFF;">
  <%= f.label :body %><br>
  <%= f.rich_text_area :body %><br>
  </div>
  <%= f.label :tags %><br>
  <%= f.text_field :tags %><br>
  <%= f.label :category %><br>
  <%= f.text_field :category %><br>
  <%= f.label :published %>
  <%= f.check_box :published %><br>
  <%= f.submit %>
<% end %>

app/views/admin/posts/_new_post_form.html.erb
<%= form_for(@post, url: admin_posts_path) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <div style="background:#FFFFFF;">
  <%= f.label :body %><br>
  <%= f.rich_text_area :body %><br>
  </div>
  <%= f.label :tags %><br>
  <%= f.text_field :tags %><br>
  <%= f.label :category %><br>
  <%= f.text_field :category %><br>
  <%= f.label :published %>
  <%= f.check_box :published %><br>
  <%= f.submit %>
<% end %>

app/views/admin/posts/edit.html.erb
<%= render 'edit_post_form' %>

app/views/admin/posts/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Edit Link</th>
        <th>Delete Link</th>
      </tr>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td>
              <%= post.title %>
            </td>
            <td>
              <%= link_to 'Edit', edit_admin_post_path(post) %>
            </td>
            <td>
              <%= link_to 'Destroy', admin_post_path(post), method: :delete, data: {confirm: 'Delete Post?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
  <p style="background:white;">
    <%= link_to 'New', new_admin_post_path %>
    <p>
</div>

app/views/admin/posts/new.html.erb
<%= render 'new_post_form' %>

app/views/admin/posts/show.html.erb
<div class="container post-show-page"> 
  <section class="hero is-dark">
    <div class="hero-body">
      <h1 class="title">
        <%= @post.title %>
      </h1>
      <h6 class="subtitle">
        <%= @post.publishedTime %>
      </h6>
    </div>
  </section>
</div>
<div class="container post-show-page" id="post-show-body">
  <%= raw @post.body %>
</div>

app/views/downloads/_edit_download.html.erb
<% @post.downloads.each do |download| %>
  <%= form_for [@post, download] do |f| %>
   <%= f.label :file %>
   <%= f.text_field :file %>
   <%= f.label :description %>
   <%= f.text_field :description %>
   <%= f.submit %>
 <% end %>
<% end  %>

app/views/downloads/_new_download.html.erb
<%= form_for @download do |f| %>
  <%= f.label :file %>
  <%= f.text_field :file %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.collection_check_boxes :post_ids, Post.all, :id, :title %>
  <%= f.submit %>
<% end %>

app/views/downloads/edit.html.erb
<%= render 'new_download' %>

app/views/downloads/index.html.erb
<h1>Download index page</h1>

<% @downloads.each do |download| %>
  <p><%= download.file %></p>
  <p><%= download.description %></p>
  <%= link_to 'Edit', edit_download_path(download) %><hr>
<% end %>

app/views/downloads/new.html.erb
<%= render 'new_download' %>

app/views/downloads/show.html.erb
<h1>Download</h1>
<%= @download.description %>
<%= @download.file %>
<% @download.posts.each do |post| %>
  <%= post.title %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Derektheprogrammer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          <h1>Derektheprogrammer</h1>
        </a>

        <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu" id="navMenu">
        <div class="navbar-end">
          <a class="navbar-item" href="/"> <h1>Home</h1> </a>
          <a class="navbar-item" href="/about"> <h1>About</h1> </a>
        </div>
      </div>

    </nav>
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', () => {
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        if ($navbarBurgers.length > 0) {
          $navbarBurgers.forEach( burgerItem => {

            burgerItem.addEventListener('click', () => {
              const target = burgerItem.dataset.target;
              const $target = document.getElementById(target);
              burgerItem.classList.toggle('is-active');
              $target.classList.toggle('is-active');
            });
          });
        }
      });
    </script>
    <br>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container" id="post-index-page">
  <section class="hero is-primary">
    <div class="container has-text-centered">
      <h1 class="title" id="about-title">
        My Musings
      </h1>
    </div>
  </section><br>
  <% @posts.each do |post| %>
    <a href="<%= post_path(post) %>">
      <div class="card" id="post-index-card">
        <div class="card-content">
          <h4 class="title has-text-centered" id="post-index-card-title">
            <%= post.title %>
          </h4>
          <p>
            <%= sanitize post.truncatePost %><hr>
          </p>
          <p>
            <%= post.publishedTime %>
          </p>
        </div>
      </div>
    </a><br>
  <% end  %>
</div>

app/views/posts/show.html.erb
<div class="container post-show-page"> 
  <section class="hero is-dark">
    <div class="hero-body">
      <h1 class="title">
        <%= @post.title %>
      </h1>
      <h6 class="subtitle">
        <%= @post.publishedTime %>
      </h6>
    </div>
  </section>
</div>
<div class="container post-show-page" id="post-show-body">
  <%= raw @post.body %>
</div>

app/views/static_pages/about.html.erb
<div class="container card">

  <div class="has-text-centered">
    <h1 class="title">
      About Me
    </h1>
  </div>
  <div class="container" id="about">
    <p>
      I am an "Autodidact", which is just a fancy word for self-taught, programmer. I have been working on my craft for about four and a half years at this point. I got my start in programming in college where I learned to program CNC machinery. I then evolved that into arduino programming, and then I jumped headfirst into Linux, and started learning Java. Currently my favorite programming languages, are Kotlin, Ruby, and Java. Rust is closely approaching landing on that list though.
    </p><br>
    <p>
      This is my website where I post about new projects I'm working on, new tools I've found, and all kinds of other things. I'm currently migrating the site from Rails 5.2, to 6.0, so content will be lacking until that transition is done. You can view it's progress, and look at other projects of mine, on my gitlab, <a href="https://gitlab.com/derek52">here.</a>
    </p>
  </div><br>

  <div class="has-text-centered">
    <h1 class="title">
      About My Setup
    </h1>
  </div>
  <div class="container" id="about">
    <p>
      <%= image_tag "my_setup.jpg", :id => "setup-image"%>
    </p>
    <p>
      This is my setup where I develop things, like this very website. I'm running a custom PC, in an ancient Emachine case. I develop on Arch Linux, but my computer also boots elementaryOS, and Windows7. This photo shows my website running in development mode, while I edit my website in my favorite text editor, VIM.
    </p>
  </div>

  <div class="container has-text-centered">
    <h1 class="title">
      About This Site
    </h1>
  </div>
  <div class="container" id="about">
    <p>
      I'm a programmer, and a DIY guy, and this site is no exception. I built this site with Ruby on Rails and host it on a VPS I rent from Linode. The VPS runs Ubuntu 18.04 Bionic Beaver(an amazing OS name). This webpage is served with Nginx+Phusino Passenger. This site would not be possible without these frameworks and applications, and I am proud to give them the credit they are due.
    </p><br>
    <div class="columns">
      <div class="column">
        <a href="https://www.rubyonrails.org" target="_blank">
          <%= image_tag "rails-logo.svg", :id => "about-image" %><br>
          Ruby On Rails
        </a>
      </div>
      <div class="column">
        <a href="https://www.ubuntu.com" target="_blank">
          <%= image_tag "ubuntu_orange_st_hex.png", :id => "about-image" %><br>
          Ubuntu
        </a>
      </div>
      <div class="column">
        <a href="https://www.linode.com" target="_blank">
          <%= image_tag "linode-logo.svg", :id => "about-image" %><br>
          Linode
        </a>
      </div>
      <div class="column">
        <a href="https://nginx.org" target="_blank">
          <%= image_tag "nginx-logo.svg", :id => "about-image" %><br>
          Nginx
        </a>
      </div>
      <div class="column">
        <a href="https://phusionpassenger.com" target="_blank">
          <%= image_tag "passenger-logo.svg", :id => "about-image" %><br>
          Phusion Passenger
        </a>
      </div>
    </div>
  </div><br><br>

  <div class="container has-text-centered">
    <h1 class="title">
      Support this site
    </h1>
    <p>
      Thanks for visiting derektheprogrammer.pizza. Consider buying a slice by sending 0.001 ethereum to the address below.
    </p>
    <p>
      My Ether address: 0x548D34b05915be1F024c60F1a5796AA084A99800
    </p>
  </div>
</div>